drop table if exists brain_teaser;
create table brain_teaser (
  id integer generated by default as identity primary key,
  name text,
  difficulty text,
  shopLink text
);

drop table if exists wookie;
create table wookie (
  id integer generated by default as identity primary key,
  name text,
  birth_year text,
  height integer,
  mass float,
  hair_color text
);

drop table if exists droid;
create table droid (
  id integer generated by default as identity primary key,
  name text,
  birth_year text,
  height integer,
  mass float,
  model text
);